#! /bin/sh

# AUTOSTART
killall shxkd && pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
numlockx &
nm-applet &
feh --bg-fill $HOME/Pictures/1.png
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# MONITOR
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# GENERAL
bspc config automatic_scheme            longest_side #spiral
bspc config border_width                2
bspc config borderless_monocle          true
bspc config bottom_padding              5
bspc config focus_follows_pointer       true
bspc config gapless_monocle             true
bspc config initial_polarity            second_child
bspc config left_padding                5
bspc config pointer_action1             move
bspc config pointer_action3             resize_corner
bspc config pointer_modifier            mod4
bspc config right_padding               5
bspc config single_monocle              true
bspc config split_ratio                 0.58
bspc config top_padding                 27
bspc config window_gap                  5

# COLORS
bspc config focused_border_color        "#65a1d8"
bspc config normal_border_color         "#839496"
bspc config presel_feedback_color       "#839496"

# RULES

# external
bspc config external_rules_command "$HOME/.config/bspwm/spotify_rule"

# # W1 #
bspc rule -a Terminator               state=floating
bspc rule -a Gnome-calculator         state=floating
bspc rule -a Pavucontrol              state=floating
bspc rule -a Blueman-manager          state=floating
# # W2 #
bspc rule -a firefox			            desktop='^2' state=tiled follow=on
# # W3 #
bspc rule -a Pcmanfm			            desktop='^3' state=tiled follow=on
# # W4 #
bspc rule -a Spotify			            desktop='^4' state=tiled
# # W5 #
bspc rule -a TelegramDesktop		      desktop='^5' state=floating follow=on
# # W6 #
bspc rule -a Soffice                  desktop='^6' state=tiled follow=on
bspc rule -a Gedit			              desktop='^6' state=tiled follow=on
bspc rule -a code-oss			            desktop='^6' state=tiled follow=on
# # W7 #
bspc rule -a VirtualBoxVM             desktop='^7' state=tiled follow=on
# # W8 #
bspc rule -a VirtualBox\ Manager      desktop='^8' state=floating follow=on
# # W9 #
bspc rule -a Anydesk			            desktop='^8' state=tiled follow=on
# # W0 #
bspc rule -a Binance                  desktop='^0' follow=on
bspc rule -a Exodus			              desktop='^0' state=tiled follow=on
bspc rule -a monero-core		          desktop='^0' state=tiled follow=on
